version: "3"
services:
  my-mongo:
    build: ./database
    image: "dagike/games_db"
    ports:
      - "27017:27017"
  my-api:
    build: ./api
    depends_on:
      - my-mongo
    image: "dagike/games_api"
    ports:
      - "80:80"
  # my-client:
  #   build: ./client
  #   depends_on:
  #     - my-mongo
  #     - my-api
  #   #   links:
  #   #     - my-api
  #   image: "dagike/games_client"
  #   ports:
  #     - "3000:3000"
